#!/usr/bin/env bash

host=""
test "$HOST" != "" && host=$HOST
test "$HOSTNAME" != "" && host=$HOSTNAME

stty erase ^H
ret=$?
while [ true ];do
    if [ "$ret" != 0 ];then
        echo -ne "\033[31m $USER@$host:$PWD \033[0m"
    else
        echo -ne "\033[32m $USER@$host:$PWD \033[0m"
    fi
    read cmd
    bash -c "$cmd"
    ret=$?
done
